export const constants = {
  initialStore: {
    home: false,
    sections: [
      {
        id: 1,
        type: 'section1',
        title: 'Section One',
        icon: 'file-empty',
        mode: 'user',
      },
      {
        id: 2,
        type: 'section2',
        title: 'Section Two',
        icon: 'file-text2',
        mode: 'user',
      },
      {
        id: 3,
        type: 'section3',
        title: 'Section Three',
        icon: 'folder',
        mode: 'user',
      },
      {
        id: 4,
        type: 'section4',
        title: 'Section Four',
        icon: 'file-zip',
        mode: 'user',
      },
      {
        id: 6,
        type: 'settings',
        title: 'Settings',
        icon: 'cog',
        mode: 'service',
      },
      {
        id: 7,
        type: 'reference',
        title: 'Reference',
        icon: 'info',
        mode: 'service',
      },
    ],
    windows: [],
    tabs: [],
  },
  windowObject: {
    key: null,
    section: null,
    minimized: false,
    maximized: false,
    x: 0,
    y: 0,
    width: 700,
    height: 500,
  },
  actions: {
    TOGGLE_HOME_MENU: 'TOGGLE_HOME_MENU',
    RENAME_SECTION: 'RENAME_SECTION',
    ADD_TAB: 'ADD_TAB',
    REMOVE_TAB: 'REMOVE_TAB',
    REPLACE_TAB: 'REPLACE_TAB',
    OPEN_WINDOW: 'OPEN_WINDOW',
    MINIMIZE_WINDOW: 'MINIMIZE_WINDOW',
    MAXIMIZE_WINDOW: 'MAXIMIZE_WINDOW',
    DRAG_WINDOW: 'DRAG_WINDOW',
    RESIZE_WINDOW: 'RESIZE_WINDOW',
    CLOSE_WINDOW: 'CLOSE_WINDOW',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_ERROR: 'AUTH_ERROR',
    AUTH_LOAD: 'AUTH_LOAD',
    SET_CONTEXT: 'SET_CONTEXT',
    CLEAR_CONTEXT: 'CLEAR_CONTEXT',
    SET_THEME: 'SET_THEME',
    SET_BG: 'SET_BG',
  },
};
